version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ./backend/
    env_file: .env
    volumes:
      - media:/media
  frontend:
    env_file: .env
    image: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static