version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ahmedzulkarnaev/kittygram_backend
    env_file: .env
    volumes:
      - media:/backend_static/
  frontend:
    env_file: .env
    build: ahmedzulkarnaev/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ahmedzulkarnaev/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static